@extends('layouts.main')
@section('policy-content')
	<main>
	@php
	 $slider=App\Models\Slider::find(1);
	@endphp
	<main>
		<section id="hero_in" class="courses" style="height: 550px;">
			<div class="wrapper">	
					<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-interval="2800" data-pause="false">	
					  <div class="carousel-inner">
					    <div class="carousel-item active">
					      <img class="d-block w-100 carousel-img" src="{{asset('assets/img/'.$slider->slider1)}}" alt="First slide">
					    </div>
					    <div class="carousel-item">
					      <img class="d-block w-100 carousel-img" src="{{asset('assets/img/'.$slider->slider2)}}" alt="Second slide">
					    </div>
					    <div class="carousel-item">
					      <img class="d-block w-100 carousel-img" src="{{asset('assets/img/'.$slider->slider3)}}" alt="Third slide">
					    </div>
					  </div>
					  <div id="search-box-container" class="col-md-8 col-sm-10">
							<div class="container search-container-inside">
								<h1 class="fadeInUp"><span></span>Privacy Policy</h1>
								
							</div>
						</div>
					</div>
				</div>
			{{--	<div class="wrapper">
					<div class="container">
						<h1 class="fadeInUp"><span></span>Online courses</h1>
					</div>
				</div> --}}
		</section>

		<div class="bg_color_1">
			<div class="container margin_120_95">
				<div class="main_title_2">
					<span><em></em></span>
					<h2>Privacy Policies</h2>
					
				</div>
				<div class="row justify-content-between p-3" style="border: solid 1px #efefef;">
					{{--<div class="col-lg-6 wow" data-wow-offset="150">
						<figure class="block-reveal">
							<div class="block-horizzontal"></div>
							<img src="{{asset('assets/img/privacy.svg')}}" class="img-fluid" alt="">
						</figure>
					</div>--}}
					<div class="col-lg-12">
						<p> (“CareerCognitive”), cares about your privacy. This privacy policy details what information is collected and how it is used and applies to visits made through this Website. This privacy policy covers all of CareerCognitive.in. It does not, however, apply to entities that CareerCognitive.in does not own or control. By using or accessing the Website, you agree to our privacy practices outlined here.</p>

<p><strong>No information from children under age 13</strong><br>
If you are under age 13, please do not attempt to register for CareerCognitive or provide any personal information about yourself to us. If we learn that we have collected personal information from a child under age 13, we will delete that information as quickly as possible.</p>

<p><strong>Surfing Data</strong><br>
When you visit any page on the Website, we use standard web server log files to collect information on the efficiency and working of the Website. This information includes the number of times a web page is accessed, the browser used, paths taken when moving through the Website, and search terms entered by users. We keep this information for an indefinite time to improve the operation of the Website and to prepare anonymous data compilations regarding traffic on the Website.</p>

<p><strong>Collection and Use of Information</strong><br>
Enquiry and Lead
When you sign up/enquire/contact on CareerCognitive.in, you provide us with your name, email, gender, birth date and other details.</p>
<p>
We also collect and store your Personal Information, if you voluntarily enter it or permit us to collect by permitting various third party login and personal details access. This information is forwarded to our email service provider and passed on to the Colleges/Universities or services you identify (or sometimes to a third party partner or vendor under contract with a Colleges/Universities or service you identify) in an email generated by our email service provider, so that the Colleges/Universities, services or third party partners or vendors may contact you with more information. In addition, we use this information to match you with Colleges/Universities based on various factors including preferences. We also share this information with our email service provider for the purpose of delivering a transaction confirmation to you. Other Personal Information may be shared as required to fulfill your information request or to notify you when a third party provides a product or service that we feel may be of interest to you. We may also share your Personal Information with third parties in order that they may send you information about their products or services when you have expressly consented to our doing so, such as by clicking a checkbox on the Website. Use of your Personal Information by a Colleges/Universities, service or third party is governed by such Colleges/Universities, service's or third party's privacy policy. We will not share your Personal Information with anyone except as provided in this privacy policy.</p>

<p><strong>Non-Personal information and Cookies</strong><br>
When you visit and interact with the Website, we may collect non-personal information such as a catalog of the site pages you visit or your IP address. CareerCognitive does use cookies (small files put on your computer).</p>

<p><strong>Colleges/Universities Contacting You</strong><br>
Different Colleges/Universities and services have different methods of following up with student information requests. Some will send brochures in the mail, while others will reply via email, SMS, and other type of messaging or try to contact individuals by telephone. By using our service to request information from Colleges/Universities or services, you are giving permission to the Colleges/Universities or services (or their partners or vendors) to contact you, using the method of their choice, to fulfill your information request.</p>

<p><strong>Sharing information on CareerCognitive</strong><br>
This section explains how your privacy settings work, and how your information is shared on CareerCognitive. You should always consider your privacy settings before sharing information on CareerCognitive.</p>

<p><strong>Other sites</strong><br>
This Privacy Policy applies to CareerCognitive services only. We do not exercise control over the links from within our various services. These other sites may place their own cookies or other files on your computer, collect data or solicit personal information from you. In addition, we may use the information we collect to:</p>

<p>Provide, maintain, protect, and improve our services (including advertising services) and develop new services; and protect the rights or property of CareerCognitive or our users.</p>

<p><strong>Privacy Policy Changes</strong><br>
We reserve the right to change this Privacy Policy at any time. You agree to this Privacy Policy, and any changes to the same, by visiting this Website. Therefore, we encourage you to review changes to our privacy policy every time you visit this Website.</p>

<p><strong>Security</strong><br>
CareerCognitive has established safeguards to help prevent unauthorized access to or misuse of your personal information, but cannot guarantee that your personally identifiable information will never be disclosed in a manner inconsistent with this Privacy Policy (for example, as a result of unauthorized acts by third parties that violate applicable law or relevant Web policies).</p>

<p><strong>Contact</strong><br>
We invite you to contact us if you have questions about our privacy policy at info at CareerCognitive.in</p>
					</div>
				</div>
				<!--/row-->
			</div>
			<!--/container-->
		</div>
		<!--/bg_color_1-->		
	</main>
@endsection